# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "32f98ac4afe3e1eb8bb677e4239ebad1"
name = "Custom Dashboard"
application_url = "https://atulya-jewellers-custom-dashboard.vercel.app/"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update" 

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://atulya-jewellers-custom-dashboard.vercel.app//auth/callback",
  "https://atulya-jewellers-custom-dashboard.vercel.app//auth/shopify/callback"
]